import type { SourceMetadata } from "../source/types.js";
import type { CapturedElement } from "./types.js";

const AUTO_GENERATED_ID_PATTERNS = [
	/^[0-9a-f]{8,}$/i,
	/^:r[0-9a-z]+:$/,
	/^react-/,
	/^ember\d/,
	/^__next/,
	/^radix-/,
];

function isAutoGeneratedId(id: string): boolean {
	return AUTO_GENERATED_ID_PATTERNS.some((p) => p.test(id));
}

function escapeStr(str: string): string {
	return str.replace(/'/g, "\\'");
}

function buildShadowHostSelector(host: NonNullable<CapturedElement["shadowHost"]>): string {
	if (host.testId) return `[data-testid="${host.testId}"]`;
	if (host.id) return `#${host.id}`;
	if (host.className) {
		const firstClass = host.className.trim().split(/\s+/)[0];
		if (firstClass) return `${host.tag}.${firstClass}`;
	}
	return host.tag;
}

function buildFrameLocatorPrefix(element: CapturedElement): string | null {
	if (!element.frameSelector && !element.frameName && !element.frameUrl) return null;
	if (element.frameName) {
		return `page.frameLocator('iframe[name="${escapeStr(element.frameName)}"]')`;
	}
	if (element.frameSelector) {
		return `page.frameLocator('${escapeStr(element.frameSelector)}')`;
	}
	if (element.frameUrl) {
		const url = new URL(element.frameUrl);
		return `page.frameLocator('iframe[src*="${escapeStr(url.pathname)}"]')`;
	}
	return null;
}

export interface LocatorStrategy {
	primary: string;
	fallbacks: string[];
	confidence: number; // 0-1
	concerns: string[];
}

function generateSourceAwareLocator(
	element: CapturedElement,
	sourceMetadata: SourceMetadata,
): LocatorStrategy | null {
	const src = `${sourceMetadata.filePath}:${sourceMetadata.line}`;
	if (sourceMetadata.testId) {
		return {
			primary: `page.getByTestId('${escapeStr(sourceMetadata.testId)}')`,
			fallbacks:
				element.role && element.ariaLabel
					? [`page.getByRole('${element.role}', { name: '${escapeStr(element.ariaLabel)}' })`]
					: [],
			confidence: 0.97,
			concerns: [`Source-verified from ${src}`],
		};
	}
	if (sourceMetadata.ariaLabel && sourceMetadata.role) {
		return {
			primary: `page.getByRole('${sourceMetadata.role}', { name: '${escapeStr(sourceMetadata.ariaLabel)}' })`,
			fallbacks: [],
			confidence: 0.95,
			concerns: [`Source-verified from ${src}`],
		};
	}
	return null;
}

function generateDOMLocator(
	element: CapturedElement,
	displayText: string | null | undefined,
	fallbacks: string[],
): { primary: string; confidence: number; concern: string | null } {
	if (element.role && element.ariaLabel) {
		const primary = `page.getByRole('${element.role}', { name: '${escapeStr(element.ariaLabel)}' })`;
		if (element.parentTestId) {
			fallbacks.push(
				`page.getByTestId('${escapeStr(element.parentTestId)}').getByRole('${element.role}', { name: '${escapeStr(element.ariaLabel)}' })`,
			);
		}
		if (element.parentRole) {
			fallbacks.push(
				`page.locator('[role="${element.parentRole}"]').getByRole('${element.role}', { name: '${escapeStr(element.ariaLabel)}' })`,
			);
		}
		return { primary, confidence: 0, concern: null };
	}
	if (element.role && displayText && displayText.length < 50) {
		const primary = `page.getByRole('${element.role}', { name: '${escapeStr(displayText)}' })`;
		if (element.parentTestId) {
			fallbacks.push(
				`page.getByTestId('${escapeStr(element.parentTestId)}').getByRole('${element.role}', { name: '${escapeStr(displayText)}' })`,
			);
		}
		return { primary, confidence: 0, concern: null };
	}
	if (element.testId) {
		return {
			primary: `page.getByTestId('${escapeStr(element.testId)}')`,
			confidence: 0.95,
			concern: null,
		};
	}
	if (element.placeholder) {
		return {
			primary: `page.getByPlaceholder('${escapeStr(element.placeholder)}')`,
			confidence: 0,
			concern: null,
		};
	}
	if (displayText && displayText.length < 30 && !displayText.includes("\n")) {
		return {
			primary: `page.getByText('${escapeStr(displayText)}')`,
			confidence: 0.7,
			concern: null,
		};
	}
	if (element.id && !isAutoGeneratedId(element.id)) {
		return { primary: `page.locator('#${element.id}')`, confidence: 0, concern: null };
	}
	if (element.name) {
		return { primary: `page.locator('[name="${element.name}"]')`, confidence: 0, concern: null };
	}
	return {
		primary: `page.locator('${element.cssSelector}')`,
		confidence: 0.4,
		concern: "Using CSS fallback; consider adding data-testid",
	};
}

function addSiblingFallbacks(
	element: CapturedElement,
	primary: string,
	confidence: number,
	fallbacks: string[],
	concerns: string[],
): void {
	if (
		element.siblingIndex === undefined ||
		element.siblingCount === undefined ||
		element.siblingCount <= 1 ||
		confidence >= 0.8
	) {
		return;
	}
	if (element.siblingIndex === 0) {
		fallbacks.push(`${primary}.first()`);
	} else {
		fallbacks.push(`${primary}.nth(${element.siblingIndex})`);
	}
	concerns.push(
		`Element is ${element.siblingIndex === 0 ? "first" : `at position ${element.siblingIndex}`} among ${element.siblingCount} siblings`,
	);
}

export function generateLocator(
	element: CapturedElement,
	sourceMetadata?: SourceMetadata | null,
): LocatorStrategy {
	const concerns: string[] = [];
	const fallbacks: string[] = [];
	let confidence = 0.9;

	// Determine iframe prefix (frameLocator replaces 'page' as the root)
	const framePrefix = buildFrameLocatorPrefix(element);
	const isInIframe = framePrefix !== null;

	// Determine shadow DOM prefix
	const shadowHost = element.shadowHost;
	const shadowDepth = element.shadowDepth ?? 0;
	const isInShadow = shadowHost !== undefined && shadowHost !== null && shadowDepth > 0;

	if (isInIframe) {
		concerns.push(
			`Element is inside an iframe${element.frameName ? ` (name="${element.frameName}")` : ""}`,
		);
		confidence -= 0.1;
	}

	if (isInShadow) {
		concerns.push(`Element is inside shadow DOM (depth ${shadowDepth})`);
		confidence -= 0.1;
	}

	if (sourceMetadata) {
		const sourceResult = generateSourceAwareLocator(element, sourceMetadata);
		if (sourceResult) {
			return applyShadowAndFramePrefix(sourceResult, element, framePrefix, isInShadow);
		}

		if (sourceMetadata.ariaLabel) {
			const src = `${sourceMetadata.filePath}:${sourceMetadata.line}`;
			concerns.push(`Source-mapped from ${src} (${sourceMetadata.componentName})`);
			confidence = 0.95;
		}
	}

	const displayText =
		element.mightBeDynamic && element.stableText ? element.stableText : element.text;

	if (element.mightBeDynamic) {
		concerns.push("Contains dynamic content; using stable text portion");
		confidence -= 0.1;
	}

	if (element.siblingCount && element.siblingCount > 1) {
		confidence -= 0.15;
	}

	const dom = generateDOMLocator(element, displayText, fallbacks);
	let primary = dom.primary;
	if (dom.confidence !== 0) confidence = dom.confidence;
	if (dom.concern) concerns.push(dom.concern);

	addSiblingFallbacks(element, primary, confidence, fallbacks, concerns);

	if (element.nearbyHeading && concerns.length > 0) {
		concerns.push(`Located in section: "${element.nearbyHeading}"`);
	}

	// Apply shadow DOM locator chaining
	if (isInShadow && shadowHost) {
		const hostSelector = buildShadowHostSelector(shadowHost);
		primary = rewriteLocatorWithShadowHost(primary, hostSelector);
		for (let i = 0; i < fallbacks.length; i++) {
			const fb = fallbacks[i];
			if (fb) fallbacks[i] = rewriteLocatorWithShadowHost(fb, hostSelector);
		}
	}

	// Apply iframe frameLocator prefix
	if (isInIframe && framePrefix) {
		primary = primary.replace(/^page\./, `${framePrefix}.`);
		for (let i = 0; i < fallbacks.length; i++) {
			const fb = fallbacks[i];
			if (fb) fallbacks[i] = fb.replace(/^page\./, `${framePrefix}.`);
		}
	}

	// Clamp confidence to [0, 1]
	confidence = Math.max(0, Math.min(1, confidence));

	return { primary, fallbacks, confidence, concerns };
}

function rewriteLocatorWithShadowHost(locator: string, hostSelector: string): string {
	return locator.replace(/^page\./, `page.locator('${hostSelector}').`);
}

function applyShadowAndFramePrefix(
	strategy: LocatorStrategy,
	element: CapturedElement,
	framePrefix: string | null,
	isInShadow: boolean,
): LocatorStrategy {
	const shadowHost = element.shadowHost;
	const shadowDepth = element.shadowDepth ?? 0;

	let { primary } = strategy;
	const fallbacks = [...strategy.fallbacks];
	let { confidence } = strategy;
	const concerns = [...strategy.concerns];

	if (isInShadow && shadowHost) {
		const hostSelector = buildShadowHostSelector(shadowHost);
		primary = rewriteLocatorWithShadowHost(primary, hostSelector);
		for (let i = 0; i < fallbacks.length; i++) {
			const fb = fallbacks[i];
			if (fb) fallbacks[i] = rewriteLocatorWithShadowHost(fb, hostSelector);
		}
		concerns.push(`Element is inside shadow DOM (depth ${shadowDepth})`);
		confidence -= 0.1;
	}

	if (framePrefix) {
		primary = primary.replace(/^page\./, `${framePrefix}.`);
		for (let i = 0; i < fallbacks.length; i++) {
			const fb = fallbacks[i];
			if (fb) fallbacks[i] = fb.replace(/^page\./, `${framePrefix}.`);
		}
		concerns.push(
			`Element is inside an iframe${element.frameName ? ` (name="${element.frameName}")` : ""}`,
		);
		confidence -= 0.1;
	}

	confidence = Math.max(0, Math.min(1, confidence));

	return { primary, fallbacks, confidence, concerns };
}
