import type { SourceMetadata } from "../source/types.js";
import type { CapturedElement } from "./types.js";

const AUTO_GENERATED_ID_PATTERNS = [
	/^[0-9a-f]{8,}$/i,
	/^:r[0-9a-z]+:$/,
	/^react-/,
	/^ember\d/,
	/^__next/,
	/^radix-/,
];

function isAutoGeneratedId(id: string): boolean {
	return AUTO_GENERATED_ID_PATTERNS.some((p) => p.test(id));
}

function escapeStr(str: string): string {
	return str.replace(/'/g, "\\'");
}

export interface LocatorStrategy {
	primary: string;
	fallbacks: string[];
	confidence: number; // 0-1
	concerns: string[];
}

function generateSourceAwareLocator(
	element: CapturedElement,
	sourceMetadata: SourceMetadata,
): LocatorStrategy | null {
	const src = `${sourceMetadata.filePath}:${sourceMetadata.line}`;
	if (sourceMetadata.testId) {
		return {
			primary: `page.getByTestId('${escapeStr(sourceMetadata.testId)}')`,
			fallbacks:
				element.role && element.ariaLabel
					? [`page.getByRole('${element.role}', { name: '${escapeStr(element.ariaLabel)}' })`]
					: [],
			confidence: 0.97,
			concerns: [`Source-verified from ${src}`],
		};
	}
	if (sourceMetadata.ariaLabel && sourceMetadata.role) {
		return {
			primary: `page.getByRole('${sourceMetadata.role}', { name: '${escapeStr(sourceMetadata.ariaLabel)}' })`,
			fallbacks: [],
			confidence: 0.95,
			concerns: [`Source-verified from ${src}`],
		};
	}
	return null;
}

function generateDOMLocator(
	element: CapturedElement,
	displayText: string | null | undefined,
	fallbacks: string[],
): { primary: string; confidence: number; concern: string | null } {
	if (element.role && element.ariaLabel) {
		const primary = `page.getByRole('${element.role}', { name: '${escapeStr(element.ariaLabel)}' })`;
		if (element.parentTestId) {
			fallbacks.push(
				`page.getByTestId('${escapeStr(element.parentTestId)}').getByRole('${element.role}', { name: '${escapeStr(element.ariaLabel)}' })`,
			);
		}
		if (element.parentRole) {
			fallbacks.push(
				`page.locator('[role="${element.parentRole}"]').getByRole('${element.role}', { name: '${escapeStr(element.ariaLabel)}' })`,
			);
		}
		return { primary, confidence: 0, concern: null };
	}
	if (element.role && displayText && displayText.length < 50) {
		const primary = `page.getByRole('${element.role}', { name: '${escapeStr(displayText)}' })`;
		if (element.parentTestId) {
			fallbacks.push(
				`page.getByTestId('${escapeStr(element.parentTestId)}').getByRole('${element.role}', { name: '${escapeStr(displayText)}' })`,
			);
		}
		return { primary, confidence: 0, concern: null };
	}
	if (element.testId) {
		return {
			primary: `page.getByTestId('${escapeStr(element.testId)}')`,
			confidence: 0.95,
			concern: null,
		};
	}
	if (element.placeholder) {
		return {
			primary: `page.getByPlaceholder('${escapeStr(element.placeholder)}')`,
			confidence: 0,
			concern: null,
		};
	}
	if (displayText && displayText.length < 30 && !displayText.includes("\n")) {
		return {
			primary: `page.getByText('${escapeStr(displayText)}')`,
			confidence: 0.7,
			concern: null,
		};
	}
	if (element.id && !isAutoGeneratedId(element.id)) {
		return { primary: `page.locator('#${element.id}')`, confidence: 0, concern: null };
	}
	if (element.name) {
		return { primary: `page.locator('[name="${element.name}"]')`, confidence: 0, concern: null };
	}
	return {
		primary: `page.locator('${element.cssSelector}')`,
		confidence: 0.4,
		concern: "Using CSS fallback; consider adding data-testid",
	};
}

function addSiblingFallbacks(
	element: CapturedElement,
	primary: string,
	confidence: number,
	fallbacks: string[],
	concerns: string[],
): void {
	if (
		element.siblingIndex === undefined ||
		element.siblingCount === undefined ||
		element.siblingCount <= 1 ||
		confidence >= 0.8
	) {
		return;
	}
	if (element.siblingIndex === 0) {
		fallbacks.push(`${primary}.first()`);
	} else {
		fallbacks.push(`${primary}.nth(${element.siblingIndex})`);
	}
	concerns.push(
		`Element is ${element.siblingIndex === 0 ? "first" : `at position ${element.siblingIndex}`} among ${element.siblingCount} siblings`,
	);
}

export function generateLocator(
	element: CapturedElement,
	sourceMetadata?: SourceMetadata | null,
): LocatorStrategy {
	const concerns: string[] = [];
	const fallbacks: string[] = [];
	let confidence = 0.9;

	if (sourceMetadata) {
		const sourceResult = generateSourceAwareLocator(element, sourceMetadata);
		if (sourceResult) return sourceResult;

		if (sourceMetadata.ariaLabel) {
			const src = `${sourceMetadata.filePath}:${sourceMetadata.line}`;
			concerns.push(`Source-mapped from ${src} (${sourceMetadata.componentName})`);
			confidence = 0.95;
		}
	}

	const displayText =
		element.mightBeDynamic && element.stableText ? element.stableText : element.text;

	if (element.mightBeDynamic) {
		concerns.push("Contains dynamic content; using stable text portion");
		confidence -= 0.1;
	}

	if (element.siblingCount && element.siblingCount > 1) {
		confidence -= 0.15;
	}

	const dom = generateDOMLocator(element, displayText, fallbacks);
	const primary = dom.primary;
	if (dom.confidence !== 0) confidence = dom.confidence;
	if (dom.concern) concerns.push(dom.concern);

	addSiblingFallbacks(element, primary, confidence, fallbacks, concerns);

	if (element.nearbyHeading && concerns.length > 0) {
		concerns.push(`Located in section: "${element.nearbyHeading}"`);
	}

	return { primary, fallbacks, confidence, concerns };
}
