import { describe, expect, it } from "vitest";
import type { BaselineDiff } from "../../../src/ci/baseline.js";
import { formatPRComment } from "../../../src/ci/github-comment.js";
import type { SecurityFinding } from "../../../src/types/results.js";

function makeFinding(overrides: Partial<SecurityFinding> & { id: string }): SecurityFinding {
	return {
		category: "headers",
		severity: "medium",
		message: "Test finding",
		remediation: "Fix it",
		...overrides,
	};
}

describe("formatPRComment", () => {
	it("formats a comment with multiple severity levels", () => {
		const findings: SecurityFinding[] = [
			makeFinding({
				id: "header-missing-csp",
				severity: "critical",
				message: "Content-Security-Policy header is missing",
				remediation:
					"Set a Content-Security-Policy header. Start with: `default-src 'self'; script-src 'self'`",
				cweId: "CWE-693",
			}),
			makeFinding({
				id: "cookie-missing-secure",
				severity: "high",
				message: 'Cookie "session" is missing the Secure flag',
				remediation: "Set the Secure flag on all session cookies.",
				cweId: "CWE-614",
				category: "cookies",
			}),
			makeFinding({
				id: "header-missing-referrer",
				severity: "medium",
				message: "Referrer-Policy header is missing",
				remediation: "Set Referrer-Policy: strict-origin-when-cross-origin",
			}),
		];

		const result = formatPRComment(findings, {
			url: "https://app.example.com",
			score: 72,
			threshold: "high",
			passed: false,
		});

		expect(result).toContain("## \u{1F512} Kovar Security Check");
		expect(result).toContain("**URL:** https://app.example.com");
		expect(result).toContain("**Score:** 72/100");
		expect(result).toContain("FAILED");
		expect(result).toContain("threshold: high");
		expect(result).toContain("Critical | 1");
		expect(result).toContain("High | 1");
		expect(result).toContain("Medium | 1");
		expect(result).toContain("Content-Security-Policy header is missing");
		expect(result).toContain("CWE-693");
		expect(result).toContain("Generated by [Kovar]");
	});

	it("formats a passing comment with no findings", () => {
		const result = formatPRComment([], {
			url: "https://secure.example.com",
			score: 100,
			threshold: "high",
			passed: true,
		});

		expect(result).toContain("PASSED");
		expect(result).toContain("**Score:** 100/100");
		expect(result).toContain("No security findings detected.");
		expect(result).not.toContain("### Details");
	});

	it("sorts findings by severity", () => {
		const findings: SecurityFinding[] = [
			makeFinding({ id: "low-1", severity: "low", message: "Low finding" }),
			makeFinding({ id: "crit-1", severity: "critical", message: "Critical finding" }),
			makeFinding({ id: "med-1", severity: "medium", message: "Medium finding" }),
		];

		const result = formatPRComment(findings, {
			url: "https://example.com",
			score: 73,
			threshold: "high",
			passed: true,
		});

		const criticalIndex = result.indexOf("Critical finding");
		const mediumIndex = result.indexOf("Medium finding");
		const lowIndex = result.indexOf("Low finding");

		expect(criticalIndex).toBeLessThan(mediumIndex);
		expect(mediumIndex).toBeLessThan(lowIndex);
	});

	it("includes CWE only when present", () => {
		const findings: SecurityFinding[] = [
			makeFinding({
				id: "with-cwe",
				severity: "high",
				message: "Has CWE",
				cweId: "CWE-123",
			}),
			makeFinding({
				id: "no-cwe",
				severity: "medium",
				message: "No CWE",
			}),
		];

		const result = formatPRComment(findings, {
			url: "https://example.com",
			score: 85,
			threshold: "high",
			passed: false,
		});

		expect(result).toContain("**CWE:** CWE-123");
		const detailsBlocks = result.split("<details>");
		const noCweBlock = detailsBlocks.find((b) => b.includes("No CWE"));
		expect(noCweBlock).toBeDefined();
		expect(noCweBlock).not.toContain("**CWE:**");
	});

	it("renders all severity icons", () => {
		const findings: SecurityFinding[] = [
			makeFinding({ id: "c1", severity: "critical", message: "Crit" }),
			makeFinding({ id: "h1", severity: "high", message: "High" }),
			makeFinding({ id: "m1", severity: "medium", message: "Med" }),
			makeFinding({ id: "l1", severity: "low", message: "Low" }),
			makeFinding({ id: "i1", severity: "info", message: "Info" }),
		];

		const result = formatPRComment(findings, {
			url: "https://example.com",
			score: 63,
			threshold: "low",
			passed: false,
		});

		expect(result).toContain("\u{1F534} Critical | 1");
		expect(result).toContain("\u{1F7E0} High | 1");
		expect(result).toContain("\u{1F7E1} Medium | 1");
		expect(result).toContain("\u{1F535} Low | 1");
		expect(result).toContain("\u26AA Info | 1");
	});

	it("uses details/summary elements for each finding", () => {
		const findings: SecurityFinding[] = [
			makeFinding({
				id: "f1",
				severity: "high",
				message: "Some issue",
				remediation: "Fix the thing",
			}),
		];

		const result = formatPRComment(findings, {
			url: "https://example.com",
			score: 90,
			threshold: "high",
			passed: false,
		});

		expect(result).toContain("<details>");
		expect(result).toContain("<summary>");
		expect(result).toContain("</summary>");
		expect(result).toContain("</details>");
		expect(result).toContain("**Remediation:** Fix the thing");
	});

	it("includes the Kovar footer link", () => {
		const result = formatPRComment([], {
			url: "https://example.com",
			score: 100,
			threshold: "high",
			passed: true,
		});

		expect(result).toContain("*Generated by [Kovar](https://github.com/Orla-Labs/kovar)*");
	});

	it("handles a single critical finding", () => {
		const findings: SecurityFinding[] = [
			makeFinding({
				id: "single-crit",
				severity: "critical",
				message: "Only one critical",
				remediation: "Fix immediately",
				cweId: "CWE-999",
			}),
		];

		const result = formatPRComment(findings, {
			url: "https://example.com",
			score: 80,
			threshold: "critical",
			passed: false,
		});

		expect(result).toContain("Critical | 1");
		expect(result).not.toContain("High |");
		expect(result).not.toContain("Medium |");
		expect(result).toContain("Only one critical");
	});

	it("shows passed status with correct emoji", () => {
		const result = formatPRComment([], {
			url: "https://example.com",
			score: 100,
			threshold: "high",
			passed: true,
		});

		expect(result).toContain("\u2705 PASSED");
	});

	it("shows failed status with correct emoji", () => {
		const findings: SecurityFinding[] = [
			makeFinding({ id: "fail", severity: "high", message: "Failure" }),
		];

		const result = formatPRComment(findings, {
			url: "https://example.com",
			score: 90,
			threshold: "high",
			passed: false,
		});

		expect(result).toContain("\u26A0\uFE0F FAILED");
	});

	it("shows new/existing/resolved sections when diff is provided", () => {
		const newFinding = makeFinding({
			id: "new-csp",
			severity: "critical",
			message: "CSP header is missing",
			remediation: "Add CSP header",
		});
		const existingFinding = makeFinding({
			id: "existing-hsts",
			severity: "high",
			message: "HSTS header is missing",
			remediation: "Add HSTS header",
		});
		const diff: BaselineDiff = {
			new: [newFinding],
			existing: [existingFinding],
			resolved: [
				{
					id: "header-missing-xcto",
					severity: "medium",
					url: "",
					firstSeen: "2026-01-01T00:00:00.000Z",
				},
			],
		};

		const result = formatPRComment([newFinding, existingFinding], {
			url: "https://app.example.com",
			score: 72,
			threshold: "high",
			passed: false,
			diff,
		});

		expect(result).toContain("### New Findings (1)");
		expect(result).toContain("These findings are new in this PR:");
		expect(result).toContain("CSP header is missing");
		expect(result).toContain("### Existing Findings (1)");
		expect(result).toContain("These findings were already present on the base branch:");
		expect(result).toContain("HSTS header is missing");
		expect(result).toContain("### Resolved (1)");
		expect(result).toContain("These findings were fixed in this PR:");
		expect(result).toContain("~~header-missing-xcto: medium~~");
		expect(result).not.toContain("### Findings");
		expect(result).not.toContain("### Details");
	});

	it("formats backward-compatible comment without diff", () => {
		const findings: SecurityFinding[] = [
			makeFinding({ id: "f1", severity: "high", message: "Some finding" }),
		];

		const result = formatPRComment(findings, {
			url: "https://example.com",
			score: 90,
			threshold: "high",
			passed: false,
		});

		expect(result).toContain("### Findings");
		expect(result).toContain("### Details");
		expect(result).toContain("Some finding");
		expect(result).not.toContain("### New Findings");
		expect(result).not.toContain("### Existing Findings");
		expect(result).not.toContain("### Resolved");
	});

	it("shows only new findings section when no existing or resolved", () => {
		const newFinding = makeFinding({
			id: "new-1",
			severity: "critical",
			message: "Brand new issue",
			remediation: "Fix it",
		});
		const diff: BaselineDiff = {
			new: [newFinding],
			existing: [],
			resolved: [],
		};

		const result = formatPRComment([newFinding], {
			url: "https://example.com",
			score: 80,
			threshold: "high",
			passed: false,
			diff,
		});

		expect(result).toContain("### New Findings (1)");
		expect(result).toContain("Brand new issue");
		expect(result).not.toContain("### Existing Findings");
		expect(result).not.toContain("### Resolved");
	});

	it("shows only resolved section when all findings are fixed", () => {
		const diff: BaselineDiff = {
			new: [],
			existing: [],
			resolved: [
				{ id: "fixed-1", severity: "high", url: "", firstSeen: "2026-01-01T00:00:00.000Z" },
				{ id: "fixed-2", severity: "medium", url: "", firstSeen: "2026-01-01T00:00:00.000Z" },
			],
		};

		const result = formatPRComment([], {
			url: "https://example.com",
			score: 100,
			threshold: "high",
			passed: true,
			diff,
		});

		expect(result).toContain("### Resolved (2)");
		expect(result).toContain("~~fixed-1: high~~");
		expect(result).toContain("~~fixed-2: medium~~");
		expect(result).not.toContain("### New Findings");
		expect(result).not.toContain("### Existing Findings");
	});

	it("shows no findings message when diff is empty", () => {
		const diff: BaselineDiff = {
			new: [],
			existing: [],
			resolved: [],
		};

		const result = formatPRComment([], {
			url: "https://example.com",
			score: 100,
			threshold: "high",
			passed: true,
			diff,
		});

		expect(result).toContain("No security findings detected.");
		expect(result).not.toContain("### New Findings");
		expect(result).not.toContain("### Existing Findings");
		expect(result).not.toContain("### Resolved");
	});
});
