/**
 * Build script: bundles browser entry points into injectable IIFE strings.
 *
 * Uses esbuild (transitive dep of tsup) to bundle each entry point into a
 * self-contained IIFE, then writes TypeScript files that export the bundled
 * code as string constants.
 *
 * Output: src/recorder/generated/{action-capture,assertion-detector,toolbar}-script.ts
 */

import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";
import * as esbuild from "esbuild";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const BROWSER_DIR = path.join(ROOT, "src", "recorder", "browser");
const OUT_DIR = path.join(ROOT, "src", "recorder", "generated");

interface EntryConfig {
	entryFile: string;
	outputName: string;
	exportName: string;
}

const entries: EntryConfig[] = [
	{
		entryFile: path.join(BROWSER_DIR, "action-capture.entry.ts"),
		outputName: "action-capture-script.ts",
		exportName: "ACTION_CAPTURE_SCRIPT",
	},
	{
		entryFile: path.join(BROWSER_DIR, "assertion-detector.entry.ts"),
		outputName: "assertion-detector-script.ts",
		exportName: "ASSERTION_DETECTOR_SCRIPT",
	},
	{
		entryFile: path.join(BROWSER_DIR, "toolbar.entry.ts"),
		outputName: "toolbar-script.ts",
		exportName: "TOOLBAR_SCRIPT",
	},
];

async function buildEntry(config: EntryConfig): Promise<void> {
	const result = await esbuild.build({
		entryPoints: [config.entryFile],
		bundle: true,
		format: "iife",
		target: "es2017",
		minify: false,
		write: false,
		platform: "browser",
		// Tree-shake unused exports from the typed modules
		treeShaking: true,
	});

	const code = result.outputFiles[0]?.text;
	if (!code) {
		throw new Error(`esbuild produced no output for ${config.entryFile}`);
	}

	// Escape backticks and ${} in the bundled code for embedding in a template literal
	const escaped = code.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");

	const tsFile = [
		"// AUTO-GENERATED by scripts/build-browser.ts -- DO NOT EDIT",
		`export const ${config.exportName} = \`${escaped}\`;`,
		"",
	].join("\n");

	const outputPath = path.join(OUT_DIR, config.outputName);
	fs.writeFileSync(outputPath, tsFile, "utf-8");
	console.log(`  Generated ${path.relative(ROOT, outputPath)} (${code.length} bytes)`);
}

async function main() {
	// Ensure output directory exists
	fs.mkdirSync(OUT_DIR, { recursive: true });

	console.log("Building browser scripts...");
	for (const entry of entries) {
		await buildEntry(entry);
	}
	console.log("Done.");
}

main().catch((err) => {
	console.error("Browser build failed:", err);
	process.exit(1);
});
