import type { SecurityFinding } from "../types/results.js";
import { summarize } from "../types/results.js";
import type { BaselineDiff, BaselineEntry } from "./baseline.js";

const SEVERITY_ICONS: Record<string, string> = {
	critical: "\u{1F534}",
	high: "\u{1F7E0}",
	medium: "\u{1F7E1}",
	low: "\u{1F535}",
	info: "\u26AA",
};

function statusEmoji(passed: boolean): string {
	return passed ? "\u2705" : "\u26A0\uFE0F";
}

function statusLabel(passed: boolean): string {
	return passed ? "PASSED" : "FAILED";
}

function buildSummaryTable(summary: ReturnType<typeof summarize>): string {
	const rows: string[] = [];
	if (summary.critical > 0) {
		rows.push(`| ${SEVERITY_ICONS.critical} Critical | ${summary.critical} |`);
	}
	if (summary.high > 0) {
		rows.push(`| ${SEVERITY_ICONS.high} High | ${summary.high} |`);
	}
	if (summary.medium > 0) {
		rows.push(`| ${SEVERITY_ICONS.medium} Medium | ${summary.medium} |`);
	}
	if (summary.low > 0) {
		rows.push(`| ${SEVERITY_ICONS.low} Low | ${summary.low} |`);
	}
	if (summary.info > 0) {
		rows.push(`| ${SEVERITY_ICONS.info} Info | ${summary.info} |`);
	}
	if (rows.length === 0) return "";
	return `| Severity | Count |\n|----------|-------|\n${rows.join("\n")}`;
}

function buildDetails(findings: SecurityFinding[]): string {
	if (findings.length === 0) return "";

	const sorted = [...findings].sort((a, b) => {
		const order = ["critical", "high", "medium", "low", "info"];
		return order.indexOf(a.severity) - order.indexOf(b.severity);
	});

	const details = sorted.map((f) => {
		const icon = SEVERITY_ICONS[f.severity] ?? "";
		const severityLabel = f.severity.charAt(0).toUpperCase() + f.severity.slice(1);
		const lines = ["<details>", `<summary>${icon} ${severityLabel}: ${f.message}</summary>`, ""];
		if (f.cweId) {
			lines.push(`**CWE:** ${f.cweId}`);
		}
		lines.push(`**Remediation:** ${f.remediation}`);
		lines.push("");
		lines.push("</details>");
		return lines.join("\n");
	});

	return details.join("\n\n");
}

function buildResolvedList(resolved: BaselineEntry[]): string {
	return resolved.map((e) => `- ~~${e.id}: ${e.severity}~~`).join("\n");
}

export function formatPRComment(
	findings: SecurityFinding[],
	options: {
		url: string;
		score: number;
		threshold: string;
		passed: boolean;
		diff?: BaselineDiff | undefined;
	},
): string {
	const summary = summarize(findings);
	const status = `${statusEmoji(options.passed)} ${statusLabel(options.passed)}`;

	const lines: string[] = [
		"## \u{1F512} Kovar Security Check",
		"",
		`**URL:** ${options.url}`,
		`**Score:** ${options.score}/100`,
		`**Status:** ${status} (threshold: ${options.threshold})`,
		"",
	];

	if (options.diff) {
		const { diff } = options;

		if (diff.new.length > 0) {
			lines.push(`### New Findings (${diff.new.length})`);
			lines.push("These findings are new in this PR:");
			lines.push("");
			lines.push(buildDetails(diff.new));
			lines.push("");
		}

		if (diff.existing.length > 0) {
			lines.push(`### Existing Findings (${diff.existing.length})`);
			lines.push("These findings were already present on the base branch:");
			lines.push("");
			lines.push(buildDetails(diff.existing));
			lines.push("");
		}

		if (diff.resolved.length > 0) {
			lines.push(`### Resolved (${diff.resolved.length})`);
			lines.push("These findings were fixed in this PR:");
			lines.push(buildResolvedList(diff.resolved));
			lines.push("");
		}

		if (diff.new.length === 0 && diff.existing.length === 0 && diff.resolved.length === 0) {
			lines.push("No security findings detected.");
		}
	} else if (findings.length > 0) {
		lines.push("### Findings");
		lines.push("");

		const table = buildSummaryTable(summary);
		if (table) {
			lines.push(table);
			lines.push("");
		}

		lines.push("### Details");
		lines.push("");
		lines.push(buildDetails(findings));
	} else {
		lines.push("No security findings detected.");
	}

	lines.push("");
	lines.push("---");
	lines.push("*Generated by [Kovar](https://github.com/Orla-Labs/kovar)*");

	return lines.join("\n");
}
